version: '3.7'
services:
  # MongoDB
  cadmus-itinera-mongo:
    image: mongo
    container_name: cadmus-itinera-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --logpath=/dev/null
    ports:
      - 27017:27017
    networks:
      - cadmus-itinera-network

  # MySql
  cadmus-itinera-mysql:
    image: mysql
    container_name: cadmus-itinera-mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    networks:
      - cadmus-itinera-network

  # Cadmus Biblio API
  cadmus-biblio-api:
    image: vedph2020/cadmus_biblio_api:4.0.0
    container_name: cadmus-biblio-api
    ports:
      - 61691:80
    depends_on:
      - cadmus-itinera-mongo
      - cadmus-itinera-mysql
    environment:
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-itinera-mongo:27017/{0}
      - CONNECTIONSTRINGS__BIBLIO=Server=cadmus-itinera-mysql;port=3306;Database={0};Uid=root;Pwd=mysql
      - SEED__BIBLIODELAY=50
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-itinera-mongo:27017/{0}-log
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
    networks:
      - cadmus-itinera-network

  # Cadmus API
  cadmus-itinera-api:
    image: vedph2020/cadmus-itinera-api:5.0.0
    container_name: cadmus-itinera-api
    ports:
      - 5052:80
    depends_on:
      - cadmus-itinera-mongo
      - cadmus-itinera-mysql
    environment:
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-itinera-mongo:27017/{0}
      - CONNECTIONSTRINGS__INDEX=Server=cadmus-itinera-mysql;port=3306;Database={0};Uid=root;Pwd=mysql
      - SEED__INDEXDELAY=50
      - MESSAGING__APIROOTURL=http://cadmusapi.azurewebsites.net
      - MESSAGING__APPROOTURL=http://cadmusapi.com/
      - MESSAGING__SUPPORTEMAIL=support@cadmus.com
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-itinera-mongo:27017/{0}-log
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
    networks:
      - cadmus-itinera-network

  # Cadmus app
  cadmus-itinera-app:
    container_name: cadmus-itinera-app
    image: vedph2020/cadmus-itinera-app:4.0.1
    ports:
      - 4200:80
    depends_on:
      - cadmus-itinera-api
      - cadmus-biblio-api
    networks:
      - cadmus-itinera-network

networks:
  cadmus-itinera-network:
    driver: bridge
