version: '3.7'
services:
  # MongoDB
  cadmus-itinera-mongo:
    image: mongo
    container_name: cadmus-itinera-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --logpath=/dev/null
    ports:
      - 27017:27017
    networks:
      - cadmus-itinera-network

  # PostgreSQL
  cadmus-itinera-pgsql:
    image: postgres
    container_name: cadmus-itinera-pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - cadmus-itinera-network

  # Biblio API
  cadmus-biblio-api:
    image: vedph2020/cadmus-biblio-api:5.0.2
    container_name: cadmus-biblio-api
    ports:
      - 61691:80
    depends_on:
      - cadmus-itinera-mongo
      - cadmus-itinera-pgsql
    environment:
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-itinera-mongo:27017/{0}
      - CONNECTIONSTRINGS__BIBLIO=Server=cadmus-itinera-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - SEED__BIBLIODELAY=50
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-itinera-mongo:27017/{0}-log
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
    networks:
      - cadmus-itinera-network

  # Cadmus API
  cadmus-itinera-api:
    image: vedph2020/cadmus-itinera-api:6.0.8
    container_name: cadmus-itinera-api
    ports:
      - 5052:80
    depends_on:
      - cadmus-itinera-mongo
      - cadmus-itinera-pgsql
    environment:
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-itinera-mongo:27017/{0}
      - CONNECTIONSTRINGS__INDEX=Server=cadmus-itinera-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-itinera-mongo:27017/{0}-log
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
      - SEED__INDEXDELAY=25
      - MESSAGING__APIROOTURL=http://cadmusapi.azurewebsites.net
      - MESSAGING__APPROOTURL=http://cadmusapi.com/
      - MESSAGING__SUPPORTEMAIL=support@cadmus.com
    networks:
      - cadmus-itinera-network

  # Cadmus app
  cadmus-itinera-app:
    container_name: cadmus-itinera-app
    image: vedph2020/cadmus-itinera-app:5.0.3
    ports:
      - 4200:80
    depends_on:
      - cadmus-itinera-api
      - cadmus-biblio-api
    networks:
      - cadmus-itinera-network

networks:
  cadmus-itinera-network:
    driver: bridge
